#!/bin/bash
echo -e "\tRUN ON REMOTE $(uname -a)\n\t$(whoami):$(pwd)"

mkdir -p /home/$(whoami)/data/$ENV/postgresql

SYSTEMD_SERVICE=$(ls *.service)
echo "\tSYSTEMD_SERVICE=$SYSTEMD_SERVICE"

if [[ "$(systemctl --user is-enabled docker)" != 'enabled' ]]
then
	echo -e "\tenabling rootless docker"
	dockerd-rootless-setuptool.sh install
fi

# Install systemd service config
cp ./$SYSTEMD_SERVICE ~/.config/systemd/user
loginctl enable-linger `whoami`
systemctl --user daemon-reload
systemctl --user enable $SYSTEMD_SERVICE

# (Re)start service
systemctl --user stop   $SYSTEMD_SERVICE
systemctl --user start  $SYSTEMD_SERVICE

# Print systemd service status
systemctl --user status $SYSTEMD_SERVICE