#!/bin/bash
echo -e "\tRUN ON REMOTE $(uname -a)\n\t$(whoami):$(pwd)"

if [[ "$(whoami)" != "root" ]]
then
	echo -e "\tre-run the script as root..."
	sudo -S ./run
fi

source .env 2> /dev/null
docker run --rm \
	-v `pwd`/database-migrations:/migrations \
	--network host \
	migrate/migrate \
	-path=/migrations/ \
	-database $DATABASE \
	$CMD