#!/bin/bash
# This script prepares systemd service configuration to run $TARGET on remote hosts

if [[ "$CMD" == "" ]]
then
	CMD="up"
fi

cat > .env <<- EOM
DATABASE="postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRESQL_HOST:$POSTGRESQL_PORT/$POSTGRESQL_DATABASE?sslmode=disable"
CMD="$CMD"
EOM
