#!/bin/bash
# This script prepares systemd service configuration to run $TARGET on remote hosts

# ExecStartPre=/usr/bin/docker pull memcached:1-alpine
cat > $SYSTEMD_SERVICE_MEMCACHED <<- EOM
[Unit]
Description=%n
After=docker.service
Requires=docker.service

[Service]
ExecStartPre=-/usr/bin/docker exec %n stop
ExecStartPre=-/usr/bin/docker rm %n
ExecStart=/usr/bin/docker run --rm --name %n --network=host memcached:1-alpine -p $PORT_MEMCACHED
Type=exec
Restart=always

[Install]
WantedBy=default.target
EOM