#!/bin/bash
echo -e "\tRUN ON REMOTE $(uname -a)\n\t$(whoami):$(pwd)"

if [[ "$(whoami)" != "root" ]]
then
	echo -e "\tre-run the script as root..."
	sudo -S ./run
fi

source ./env 2> /dev/null

systemctl --user --machine=$APP_USER@ status ${SYSTEMD_SERVICES[*]} ${SYSTEMD_SOCKETS[*]}
systemctl --user --machine=$APP_USER@ stop ${SYSTEMD_SOCKETS[*]}
systemctl --user --machine=$APP_USER@ stop ${SYSTEMD_SERVICES[*]}
# set -e
systemctl --user --machine=$APP_USER@ disable ${SYSTEMD_SOCKETS[*]}
systemctl --user --machine=$APP_USER@ disable ${SYSTEMD_SERVICES[*]}
# set +e
systemctl --user --machine=$APP_USER@ status ${SYSTEMD_SERVICES[*]} ${SYSTEMD_SOCKETS[*]}
set -e
userdel --force --remove $APP_USER
set +e
echo "removed user $APP_USER"
