#!/bin/bash
echo -e "\tRUN ON REMOTE $(uname -a)\n\t$(whoami):$(pwd)"

if [[ "$(whoami)" != "root" ]]
then
	echo -e "\tre-run the script as root..."
	sudo -S ./run
fi

SYSTEMD_SERVICE=$(ls *.service)

if [[ "$(systemctl is-enabled docker)" != 'enabled' ]]
then
	systemctl enable docker
	systemctl start docker
fi

# Install systemd service config
cp ./$SYSTEMD_SERVICE /etc/systemd/system

systemctl daemon-reload
systemctl enable $SYSTEMD_SERVICE

# (Re)start service
systemctl stop   $SYSTEMD_SERVICE
systemctl start  $SYSTEMD_SERVICE

# Print systemd service status
systemctl status $SYSTEMD_SERVICE