#!/bin/bash
# This script prepares systemd service configuration to run $TARGET on remote hosts

cat > wordpress-docker-entrypoint.sh <<- EOM
#!/bin/bash
sed -i -e 's/Listen 80/Listen $WORDPRESS_PORT/g' /etc/apache2/ports.conf
sed -i -e 's/*:80/*:$WORDPRESS_PORT/g'           /etc/apache2/sites-enabled/000-default.conf
docker-entrypoint.sh \$@
EOM

# Make wordpress container entrypoint script executable
chmod 755 wordpress-docker-entrypoint.sh

cat > .env <<- EOM
WORDPRESS_DB_HOST=127.0.0.1:$MARIADB_PORT
WORDPRESS_DB_USER=$MYSQL_USER
WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
WORDPRESS_DB_NAME=$MYSQL_DATABASE
WORDPRESS_DEBUG=1
EOM

ENV_PATH=/root/deployments/$ENV/$TARGET/active/.env

cat > $SYSTEMD_WORDPRESS_SERVICE <<- EOM
[Unit]
Description=%n
After=docker.service
Requires=docker.service

[Service]
ExecStartPre=-/usr/bin/docker stop %n
ExecStartPre=-/usr/bin/docker rm -fv %n
ExecStart=/usr/bin/docker run --rm --name %n --network=host --env-file $ENV_PATH -e WORDPRESS_CONFIG_EXTRA="define('WP_HOME','$WORDPRESS_HOME');define('WP_SITEURL','$WORDPRESS_HOME');" -v /root/deployments/$ENV/$TARGET/active/wordpress-docker-entrypoint.sh:/usr/local/bin/wordpress-docker-entrypoint.sh --entrypoint wordpress-docker-entrypoint.sh wordpress apache2-foreground
Type=exec
Restart=no

[Install]
WantedBy=default.target
EOM
