#!/bin/bash
# This script installs dependencies, + prepares env file with shell variables for remote hosts script

npm ci

cat > 'env' <<- EOM
SYSTEMD_SERVICE_APP=$SYSTEMD_SERVICE_APP
SYSTEMD_SOCKET_APP=$SYSTEMD_SOCKET_APP
EOM

cat > '.env' <<- EOM
ENV=$ENV
EOM