#!/bin/bash
# This script installs dependencies, + prepares env file with shell variables for remote hosts script

npm ci

cat > 'env' <<- EOM
SYSTEMD_APP_SERVICE=$SYSTEMD_APP_SERVICE
SYSTEMD_APP_SOCKET=$SYSTEMD_APP_SOCKET
EOM

cat > '.env' <<- EOM
ENV=$ENV
EOM