#!/bin/bash
echo -e "\tRUN ON REMOTE $(uname -a)\n\t$(whoami):$(pwd)"

source ./env 2> /dev/null

TARGET_SOCKET_STATUS=$(systemctl --user is-enabled $SYSTEMD_APP_SOCKET)
TARGET_SERVICE_STATUS=$(systemctl --user is-enabled $SYSTEMD_APP_SERVICE)

if [[ $TARGET_SOCKET_STATUS != 'enabled' ]] || [[ $TARGET_SERVICE_STATUS != 'enabled' ]]
then
	systemctl --user daemon-reload
	systemctl --user enable $SYSTEMD_APP_SOCKET
	systemctl --user enable $SYSTEMD_APP_SERVICE
	systemctl --user start  $SYSTEMD_APP_SOCKET
fi

# Restart service. It also would be automaticaslly restarted via socket upon the call
systemctl --user stop   $SYSTEMD_APP_SERVICE
systemctl --user start  $SYSTEMD_APP_SERVICE

# Print systemd socket/service status
systemctl --user status $SYSTEMD_APP_SOCKET
systemctl --user status $SYSTEMD_APP_SERVICE $SYSTEMD_APP_SOCKET